apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  namespace: example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx-pod
  template:
    metadata:
      labels:
        app: my-nginx-pod
    spec:
      containers:
        - name: my-nginx-container
          image: nginx
          ports:
            - containerPort: 9092
