apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cronjob-contianer
          image: perl
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(100)"]