apiVersion: v1
kind: Pod
metadata:
  name: simple-service-pod
  namespace: example
  labels:
    env: prod
    type: service
spec:
  containers:
    - name: simple-service-container
      image: mhausenblas/simpleservice:0.5.0
      ports:
        - containerPort: 9876