apiVersion: v1
kind: Pod
metadata:
  name: simple-service-pod2
  namespace: example
  labels:
    env: prod
    type: service
spec:
  containers:
    - name: simple-service-container2
      image: mhausenblas/simpleservice:0.5.0
      ports:
        - containerPort: 9876
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: password